### ISSUE TITLE
Doesn't work with db2

### ISSUE THREAD

**Issue by KyleMaas** [staltz/ssb-blobs-purge#1]
This doesn't work with db2 because of the dependency on ssb-backlinks.  According to @arj03:

> The purge module needs to be converted to db2. Meaning backlinks should be replaced with a seek query. Probably a prefix query (like key).

(From here: https://github.com/arj03/ssb-browser-demo/issues/8#issuecomment-761753817)

Unfortunately, I feel like having looked at the code involved, I think it's beyond my capabilities to fix this.  So I'm hoping maybe filing this issue will help highlight the problem.  Because if this can be fixed, then I'm fairly certain I can make this work:

https://github.com/arj03/ssb-browser-demo/issues/8

**Comment by staltz** [comment]
I'll work on this, no worries

**Comment by KyleMaas** [comment]
Awesome.  Thanks!  Sorry about the lack of help on this, but I'm pretty sure I'd make more of a mess than what I'd fix on this one.

**Comment by staltz** [comment]
Works now with 1.0.0

**Comment by KyleMaas** [comment]
Excellent.  Thank you!
